// Generated by https://quicktype.io

export interface CreateStripeOrderResponse {
  id: number;
  orderNumber: string;
  deliveryAddress: string;
  city: string;
  postalCode: string;
  totalAmount: number;
  shippingCost: number;
  grandTotal: number;
  purchaseCurrency: string;
  paymentType: string;
  userId: string;
  stripeSessionId: string;
  orderStatusId: number;
  createdAt: string;
  updatedAt: string;
  orderItems: OrderItem[];
  orderStatus: OrderStatus;
}

export interface OrderItem {
  orderId: number;
  productId: number;
  sku: string;
  quantity: number;
  product: Product;
}

export interface Product {
  id: number;
  name: string;
  description: string;
  originalPrice: number;
  currentPrice: number;
  isDiscontinued: boolean;
  brandId: number;
  categoryId: number;
  createdAt: string;
  updatedAt: string;
  brand: Brand;
  images: Image[];
  attributes: Attribute[];
}

export interface Attribute {
  sku: string;
  quantity: number;
  size: Color;
  color: Color;
}

export interface Color {
  id: number;
  value: string;
}

export interface Brand {
  id: number;
  name: string;
  path: string;
}

export interface Image {
  id: number;
  imageUrl: string;
}

export interface OrderStatus {
  id: number;
  status: string;
}
