// Generated by https://quicktype.io

export interface GetProductsResponse {
  pagination: Pagination;
  products: ProductItem[];
}

export interface Pagination {
  limit: number;
  totalItems: number;
  totalPages: number;
  nextPage: number;
  previousPage: null;
  currentPage: number;
}

export interface ProductItem {
  id: number;
  name: string;
  unitPrice: number;
  isDiscontinued: boolean;
  brand: Brand;
  images: Image[];
  attributes: Attribute[];
}

export interface Attribute {
  sku: string;
  quantity: number;
}

export interface Brand {
  id: number;
  name: string;
  path: string;
}

export interface Image {
  id: number;
  imageUrl: string;
}
