// Generated by https://quicktype.io

export interface GetProductsResponse {
  pagination: Pagination;
  products: ProductItem[];
}

export interface Pagination {
  limit: number;
  totalItems: number;
  totalPages: number;
  nextPage: number;
  previousPage: null;
  currentPage: number;
}

export interface ProductItem {
  id: number;
  name: string;
  originalPrice: number;
  currentPrice: number;
  isDiscontinued: boolean;
  brand: Brand;
  images: ProductImage[];
  attributes: Attribute[];
}

export interface Attribute {
  sku: string;
  quantity: number;
  color: Color;
  size: Color;
}

export interface Color {
  id: number;
  value: Value;
}

export enum Value {
  Black = "Black",
  Blue = "Blue",
  Brown = "Brown",
  Gray = "Gray",
  L = "L",
  M = "M",
  Navy = "Navy",
  Red = "Red",
  S = "S",
  White = "White",
  Xl = "XL",
  Xs = "XS",
  Xxl = "XXL",
}

export interface Brand {
  id: number;
  name: string;
  path: string;
}

export interface ProductImage {
  id: number;
  imageUrl: string;
}
