// Generated by https://quicktype.io

export interface GetProductsResponse {
  items: ProductItem[];
  totalCount: number;
  hasMore: boolean;
}

export interface ProductItem {
  id: number;
  name: string;
  description: string;
  unitPrice: number;
  isDiscontinued: boolean;
  brandId: number;
  categoryId: number;
  createdAt: string;
  updatedAt: string;
  category: Category;
  brand: Brand;
  images: Image[];
  attributes: Attribute[];
}

export interface Attribute {
  sku: string;
  quantity: number;
  size: Color;
  color: Color;
}

export interface Color {
  id: number;
  value: string;
}

export interface Brand {
  id: number;
  name: string;
  path: string;
}

export interface Category {
  id: number;
  name: Name;
  description: string;
  path: Path;
  slug: Slug;
  updatedAt: string;
  createdAt: string;
}
// TODO: request for all products to load enums
export enum Name {
  CargoPants = "Cargo pants",
  Chinos = "Chinos",
  Pants = "Pants",
  RainFunctionPants = "Rain & function pants",
  SoftPants = "Soft pants",
}

export enum Path {
  ClothesPants = "/clothes/pants",
  ClothesPantsCargoPants = "/clothes/pants/cargo-pants",
  ClothesPantsChinos = "/clothes/pants/chinos",
  ClothesPantsRainAndFunctionPants = "/clothes/pants/rain-and-function-pants",
  ClothesPantsSoftPants = "/clothes/pants/soft-pants",
}

export enum Slug {
  Pants = "/pants",
  PantsCargoPants = "/pants/cargo-pants",
  PantsChinos = "/pants/chinos",
  PantsRainAndFunctionPants = "/pants/rain-and-function-pants",
  PantsSoftPants = "/pants/soft-pants",
}

export interface Image {
  id: number;
  imageUrl: string;
}
