// Generated by https://quicktype.io

export interface CreateStripeSessionResponse {
  id: string;
  object: string;
  after_expiration: null;
  allow_promotion_codes: null;
  amount_subtotal: number;
  amount_total: number;
  automatic_tax: AutomaticTax;
  billing_address_collection: string;
  cancel_url: string;
  client_reference_id: null;
  consent: null;
  consent_collection: null;
  currency: string;
  customer: null;
  customer_creation: string;
  customer_details: null;
  customer_email: null;
  expires_at: number;
  livemode: boolean;
  locale: null;
  metadata: Metadata;
  mode: string;
  payment_intent: string;
  payment_link: null;
  payment_method_options: Metadata;
  payment_method_types: string[];
  payment_status: string;
  phone_number_collection: PhoneNumberCollection;
  recovered_from: null;
  setup_intent: null;
  shipping: null;
  shipping_address_collection: null;
  shipping_options: any[];
  shipping_rate: null;
  status: string;
  submit_type: null;
  subscription: null;
  success_url: string;
  total_details: TotalDetails;
  url: string;
}

export interface AutomaticTax {
  enabled: boolean;
  status: null;
}

export interface Metadata {}

export interface PhoneNumberCollection {
  enabled: boolean;
}

export interface TotalDetails {
  amount_discount: number;
  amount_shipping: number;
  amount_tax: number;
}
